### ISSUE TITLE
Release to Maven Central?

### ISSUE THREAD

**Issue by darmbrust** [danka74/SnomedCTParser#3]
Hi, 

It would be really nice if your code was release on maven central, so we can easily pull it into other projects without having to first set up a local maven repo.

I've done this in the past via sonatype:
http://central.sonatype.org/pages/ossrh-guide.html
http://central.sonatype.org/pages/requirements.html
http://central.sonatype.org/pages/apache-maven.html

Its a little tedious the first time through, but once configured, you can just do a fairly standard mvn release command, and the end result will be signed and pushed to maven central.

I'm happy to help do the config if interested.

**Comment by danka74** [comment]
Hi, sounds like a good idea. I think I need to make a release first and move some of the experimental stuff ing a branch (or something). Ill gladly take any help available in progressing this though. /Daniel

Sent by MailWise<http://www.mail-wise.com/installation/4> – Your emails, with style.:)


-------- Original Message --------

**Comment by darmbrust** [comment]
Sure - sounds good.

I recently configured this little project and pushed it through:
https://github.com/VA-CTT/HK2Utilities

I integrated the sonatype maven extension, and used jGitFlow for the release process.  
Doing a release now simply consists of running:

mvn jgitflow:release-start jgitflow:release-finish -DreleaseVersion=1.4.1 -DdevelopmentVersion=1.5-SNAPSHOT -PpublicRelease

You just have to have the appropriate GPG signing key available on the system where you are doing the release, and have your credentials for your sonatype account in your local maven config.

That assumes you want to use sonatype to do the push - I think there are other mechanisms, but I'm not familiar with those.

For you to get permission to publish, you would need to make a jira account, and submit a ticket as described here:
http://central.sonatype.org/pages/ossrh-guide.html

If you are fine with using the jGitFlow release process (http://jgitflow.bitbucket.org/) I can clone  your repo, and do the maven config steps.

**Comment by darmbrust** [comment]
maven config updates are here:  https://github.com/danka74/SnomedCTParser/pull/4

With the gitflow dev model, these changes should become your develop branch, and then when you run the jgitflow build command, it will promote to master.

See the releaseNote.md file for sample release commands.  If you aren't familiar with gitflow, see http://nvie.com/posts/a-successful-git-branching-model/

Let me know if you have any issues - the next steps on your side should just be to set up the sonatype account, create the initial sonatype ticket they require, and make yourself a gpg key.

Finally, in your maven settings.xml file, add the following:

<servers>
	 <server>
		<id>ossrh</id>
		<username>[sonatype-username]</username>
		<password>[sonatype-password]</password>
	</server>
	<server>
		<id>gpg.passphrase</id>
		<passphrase>[your-gpg-passphrase]</passphrase>
	</server>

**Comment by darmbrust** [comment]
Anything else I can do to help get a release out at this point?

Thanks

**Comment by danka74** [comment]
I've been partly succesful. However, I think I misunderstood the role of the different branches in jgitflow and I get "magic" checkout conflicts when finalizing the release.
Thanks,
Daniel

**Comment by darmbrust** [comment]
I have had a few issues in the past trying to do the initial release with jgitflow, getting all the branches the way it wants it.  Your best bet, I think would be to make sure that master is merged into develop - so they are at the same place - then do the release from develop.  The end result, should be that develop ends up 1 commit ahead of master - currently, I see that master is both ahead and behind.

**Comment by danka74** [comment]
Sorry for being a newbie, but when I merge master into develop, develop gets one commit ahead of master, the "merge commit". What to do?

**Comment by darmbrust** [comment]
I think it will be ok, if develop is ahead - when you do the jgitflow release process, it should merge the released code into master.  As long as master is only behind, it should be able to automate that merge.

**Comment by danka74** [comment]
Hooray! It is (or seems to be) done! If we meet at a conference or so I'll buy you a drink.

**Comment by darmbrust** [comment]
Very cool!  I'll try pulling the new version from central later today.

Thanks!

**Comment by darmbrust** [comment]
http://mvnrepository.com/artifact/se.liu.imt.mi.snomedct/SnomedCTParser/0.1

Worked perfectly to pull from there.  Thanks again!

FYI - on the https://github.com/danka74/SnomedCTParser/branches page, you can change the 'default' branch to 'develop' rather than 'master', so folks that find your project will get the latest version of the readme upfront.

You can also now update your installation instructions to simply say:
    <dependency>
        <groupId>se.liu.imt.mi.snomedct</groupId>
        <artifactId>SnomedCTParser</artifactId>
        <version>0.1</version>
    </dependency>
